
name: 2048-github-actions

on: [push]
jobs: 

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: 17
          
      - name: Build
        run: mvn compile
      
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with: 
          name: jar-artifact
          path: target/*
          retention-days: 7
        
    
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with:
        java-version: 17
     - uses: actions/download-artifact@v2
       with:
          name: jar-artifact
            
     - name: Test
       run: mvn test
       
  package:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with:
        java-version: 17
     - uses: actions/download-artifact@v2
       with:
          name: jar-artifact
          
     - name: Package
       run: mvn package
       
     - name: Save artifact
       uses: actions/upload-artifact@v2
       with:
         name: war-artifact
         path: target/game2048.war
     
    
  deploy:
   runs-on: self-hosted
   needs: package
   
   steps:
   - uses: actions/download-artifact@v2
     with:
      name: war-artifact
      path: /usr/local/tomcat/webapps
 

       
   
   
