
name: 2048-github-actions

on: [push]
jobs: 

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: 17
          
      - name: Build
        run: mvn compile
      
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with: 
          name: jar-artifact
          path: target/*
          retention-days: 7
        
    
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with:
        java-version: 17
     - uses: actions/download-artifact@v2
       with:
          name: jar-artifact
            
     - name: Test
       run: mvn test
       
  package:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with:
        java-version: 17
     - uses: actions/download-artifact@v2
       with:
          name: jar-artifact
          
     - uses: actions/upload-artifact@v2
       with:
         name: build-artifact
         path: "target/game2048.war"
          
     - name: Package
       run: mvn package
    
  deploy:
   runs-on: self-hosted
   needs: package
   
   steps:
   
   - name: Deploy
     run : |
      - docker rm --force tomcat
      - docker image rm --force game2048
      - echo -e 'FROM tomcat:9-jdk17-openjdk-slim \n COPY ./target/game2048.war /usr/local/tomcat/webapps' | docker build -t game2048 -f- .
      - docker run --rm -d --name tomcat -p 8080:8080 game2048

       
   
   
