
name: 2048-github-actions

on: [push]
jobs: 

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: 14
          
      - name: Build
        run: mvn compile
      
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with: 
          name: jar-artifact
          path: target/*
          retention-days: 7
        
    
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
     - uses: actions/checkout@v2
     - uses: actions/download-artifact@v2
       with:
          name: jar-artifact
          path: "target/*"
            
     - name: Test
       run: mvn test
    
      
